// @ts-check
/**
 * expired-log.mjs — the standing record of postings confirmed removed.
 *
 * Until now a dead posting left only a `skipped_expired` row in scan-history.tsv,
 * which exists to stop the scanner re-checking the URL — it is dedup bookkeeping,
 * not something a person reads. So a role vanishing produced no human-legible
 * trace: no way to see what closed this week, how long a company's postings
 * survive, or whether a role you were tracking is gone or merely unverifiable.
 *
 * This writes that trace to data/expired-jobs.md as one markdown table, newest
 * removal first.
 *
 * ── ON THE DATE ───────────────────────────────────────────────────────────────
 *
 * The column is "Removed (est.)" and the estimate is the date we FIRST CONFIRMED
 * the posting gone. No ATS publishes a removal date, so that confirmation is an
 * UPPER BOUND, not the event: a posting taken down the day after a scan sits
 * undetected until the next liveness check, which can be a week later.
 *
 * The bound is only as tight as the checking cadence, which is why the header
 * written into the file says so rather than presenting the date as fact. Naming
 * the column "Removed" outright would read as a measurement, and someone would
 * eventually compute a time-to-close statistic from it.
 *
 * Once a URL is recorded its date never moves. A later re-check of the same dead
 * URL is a second observation of the same removal, and taking the later date
 * would loosen the bound every time the log is regenerated.
 *
 * ── WHAT COUNTS AS DEAD ───────────────────────────────────────────────────────
 *
 * Only a CONFIRMED `expired` verdict. `uncertain` never lands here — that is the
 * whole point of the distinction. A posting that could not be read (bot wall,
 * unrendered iframe, no apply control found) is unknown, not gone, and writing
 * it into a file titled "Expired Jobs" would launder a failed check into a fact.
 */

import { existsSync, readFileSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';
import { withPipelineLock } from './pipeline-lock.mjs';

const ROOT = dirname(fileURLToPath(import.meta.url));
export const EXPIRED_LOG_PATH = join(ROOT, 'data', 'expired-jobs.md');

const COLUMNS = ['Removed (est.)', 'Company', 'Title', 'Posted', 'Source', 'Evidence', 'URL'];

const HEADER = `# Expired Jobs

Postings confirmed removed, newest first. Written automatically whenever a
liveness check returns a definitive \`expired\` — never on an uncertain one, since
a posting that could not be read is unknown, not gone.

**Removed (est.) is the date the posting was first confirmed gone, not the date it
came down.** No ATS publishes a removal date, so this is an upper bound whose
tightness depends entirely on how often liveness runs. Do not compute
time-to-close from it.

Generated by \`expired-log.mjs\`. Rows are keyed by URL; a URL already listed keeps
its original date.
`;

/**
 * Markdown table cells are pipe-delimited, and job titles really do contain
 * pipes ("Engineer | Platform"). Escaping keeps one row one row.
 * @param {unknown} v
 */
function cell(v) {
  const s = String(v ?? '').replace(/\s+/g, ' ').trim();
  if (!s) return '—';
  return s.replace(/\\/g, '\\\\').replace(/\|/g, '\\|');
}

/** @param {string} s */
function uncell(s) {
  const v = s.trim().replace(/\\\|/g, '|').replace(/\\\\/g, '\\');
  return v === '—' ? '' : v;
}

/**
 * Read the existing log back into rows keyed by URL.
 *
 * Parsing our own output (rather than keeping a sidecar JSON) is what makes the
 * markdown file the source of truth: a row deleted by hand stays deleted, which
 * is the behaviour the rest of this project's file-canonical data has.
 *
 * @param {string} text
 * @returns {Map<string, {removed: string, company: string, title: string, posted: string, source: string, evidence: string, url: string}>}
 */
export function parseExpiredLog(text) {
  const rows = new Map();
  if (typeof text !== 'string') return rows;
  for (const line of text.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed.startsWith('|')) continue;
    // Split on unescaped pipes only.
    const parts = trimmed.slice(1).replace(/\|$/, '').split(/(?<!\\)\|/).map(uncell);
    if (parts.length < COLUMNS.length) continue;
    const [removed, company, title, posted, source, evidence, url] = parts;
    if (removed === COLUMNS[0] || /^-+$/.test(removed)) continue; // header / separator
    if (!url || !/^https?:\/\//.test(url)) continue;
    if (!rows.has(url)) rows.set(url, { removed, company, title, posted, source, evidence, url });
  }
  return rows;
}

/**
 * Sort newest-removed first, with company/title/url as tiebreakers so the file
 * is byte-stable across runs (a churning diff hides the rows that actually
 * changed).
 * @param {any[]} rows
 */
function sortRows(rows) {
  return [...rows].sort(
    (a, b) =>
      String(b.removed).localeCompare(String(a.removed)) ||
      String(a.company).localeCompare(String(b.company)) ||
      String(a.title).localeCompare(String(b.title)) ||
      String(a.url).localeCompare(String(b.url))
  );
}

/**
 * Render the whole file. Regenerated in full rather than appended to, because
 * the table is sorted — a new row rarely belongs at the end.
 * @param {any[]} rows
 */
export function formatExpiredLog(rows) {
  const sorted = sortRows(rows);
  const head = `| ${COLUMNS.join(' | ')} |\n|${COLUMNS.map(() => '---').join('|')}|`;
  const body = sorted
    .map((r) => `| ${[r.removed, r.company, r.title, r.posted, r.source, r.evidence, r.url].map(cell).join(' | ')} |`)
    .join('\n');
  const table = sorted.length ? `${head}\n${body}\n` : `${head}\n`;
  const count = sorted.length === 1 ? '1 posting' : `${sorted.length} postings`;
  return `${HEADER}\n_${count} recorded._\n\n${table}`;
}

/**
 * Merge new confirmations into existing rows.
 *
 * An already-listed URL is left exactly as it was: a second sighting of a dead
 * posting is the same removal observed later, and overwriting would loosen the
 * bound the date represents (see the note at the top of this file).
 *
 * @param {Map<string, any>} existing
 * @param {any[]} incoming
 * @returns {{rows: any[], added: number}}
 */
export function mergeExpired(existing, incoming) {
  const merged = new Map(existing);
  let added = 0;
  for (const entry of incoming) {
    const url = String(entry?.url || '').trim();
    if (!url || !/^https?:\/\//.test(url)) continue;
    if (merged.has(url)) continue;
    merged.set(url, {
      removed: entry.removed,
      company: entry.company || '',
      title: entry.title || '',
      posted: entry.posted || '',
      source: entry.source || '',
      evidence: entry.evidence || '',
      url,
    });
    added++;
  }
  return { rows: [...merged.values()], added };
}

/**
 * Normalize one confirmed-dead posting into a log row.
 *
 * Callers hand over whatever shape they have: scan.mjs has a full offer, while
 * check-liveness.mjs has a URL and a verdict and nothing else. Missing fields
 * render as "—" rather than blocking the row — a URL and a date is already the
 * record worth keeping.
 *
 * @param {{url: string, company?: string, title?: string, postedAt?: string, posted?: string, portal?: string, source?: string, code?: string, reason?: string, evidence?: string}} entry
 * @param {string} date - YYYY-MM-DD the removal was confirmed
 */
export function toExpiredRow(entry, date) {
  return {
    removed: date,
    company: entry.company || '',
    title: entry.title || '',
    posted: entry.postedAt || entry.posted || '',
    source: entry.portal || entry.source || '',
    // Prefer the stable code over the prose reason: codes are contracted
    // (liveness-core/liveness-api own them), reason wording is not.
    evidence: entry.evidence || entry.code || entry.reason || '',
    url: entry.url,
  };
}

/**
 * Record confirmed-dead postings. Idempotent — re-running with the same URLs
 * changes nothing, so it is safe to call from every liveness path.
 *
 * Shares withPipelineLock so a scan writing pipeline.md and a concurrent
 * check-liveness run cannot interleave writes.
 *
 * @param {any[]} entries - each needs at least {url}; see toExpiredRow
 * @param {{date: string, path?: string}} opts
 * @returns {Promise<{added: number, total: number, path: string}>}
 */
export async function recordExpired(entries, { date, path = EXPIRED_LOG_PATH } = /** @type {any} */ ({})) {
  if (!Array.isArray(entries) || entries.length === 0) {
    return { added: 0, total: 0, path };
  }
  return await withPipelineLock(path, async () => {
    const existing = existsSync(path) ? parseExpiredLog(readFileSync(path, 'utf-8')) : new Map();
    const { rows, added } = mergeExpired(existing, entries.map((e) => toExpiredRow(e, date)));
    writeFileSync(path, formatExpiredLog(rows), 'utf-8');
    return { added, total: rows.length, path };
  });
}
